### PR TITLE
Modify classifier hyperparameter defaults and ranges

### PR DESCRIPTION
**Pull request by agitter**
Some of our example datasets don't converge with 500 iterations.

@fmu2 do you remember whether these are the only lines that need to be edited to change the default iterations?  Do I need to change it in both places or is that redundant?

### CODE REVIEW

**Comment by agitter** [comment]
I'm generalizing this pull request to update other classifiers.  The last commit allows up to 50 estimators for the random forest.

@cmilica are there other hyperparamters you recommend modifying?

Once we're done with all the changes, I'd like to do more local testing before merging.

**Comment by cmilica** [comment]
I think that is the most important one for the upcoming workshop!

**Comment by agitter** [comment]
These screenshots document the new changes in the software:

image

image

Logistic regression now trains to completion on the T cell `size_intensity_feature.csv` dataset.  I'll merge soon if there are no objections.

**Comment by agitter** [comment]
I also made ml4bio lower case in the window title to be consistent with our latest workshop.

**Pull request merged**
